name: Semgrep

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]        # optional: scan main on push
  workflow_dispatch: {}      # optional: run on demand

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full fetch helps diff-aware behavior if needed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python -m pip install --upgrade pip && pip install semgrep

      - name: Run Semgrep (CI-safe)
        # --error makes `semgrep scan` exit 1 when findings exist (so job fails).
        run: semgrep scan --config auto --sarif --output semgrep.sarif --error

      - name: Upload SARIF to GitHub Code Scanning (optional, nice UI)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
