name: semgrep-scan

on:
  push:
    branches:
      - '**'        # run on pushes (you can restrict to PR branches if you prefer)
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep scan (auto rules)
        id: run-semgrep
        run: |
          # CLI v1.12+ uses `semgrep scan` (older docs use semgrep --config)
          semgrep scan --config auto --quiet --output semgrep-results.json || echo "::set-output name=semgrep_failed::true"

      - name: Upload semgrep JSON artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json
