name: semgrep-scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # full git history required for diff-aware scan

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep (CI mode, outputs SARIF)
        id: semgrep
        run: |
          # adjust --config to point to your .semgrep.yml, a registry pack like p/ci,
          # or a list "p/owasp-top-ten,p/ci". semgrep ci integrates nicely with GitHub Actions.
          semgrep ci --config .semgrep.yml --sarif --output semgrep.sarif --timeout 10m

      - name: Upload SARIF to GitHub Code Scanning (optional — shows results in GitHub)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
