name: semgrep-scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: SAST Scan
        id: semgrep
        run: |
          # use `semgrep ci` for better PR/diff awareness; `--error` makes semgrep scan return exit code 1 if findings exist
          run: semgrep scan --config .semgrep.yml --sarif --output semgrep.sarif --error --all-targets
        # If you prefer semgrep scan with explicit error-on-findings:
        # run: semgrep scan --config .semgrep.yml --sarif --output semgrep.sarif --error

      - name: Upload SARIF for GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
